In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
!pip install scikit-optimize
from skopt import BayesSearchCV
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from google.colab import drive

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting scikit-optimize
  Downloading scikit_optimize-0.9.0-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.3/100.3 kB 13.0 MB/s eta 0:00:00
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.2.0)
Collecting pyaml>=16.9 (from scikit-optimize)
  Downloading pyaml-23.5.9-py3-none-any.whl (17 kB)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.22.4)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.10.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.2.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from pyaml>=16.9->scikit-optimize) (6.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->scikit-optimize) (3.1.0)
Installing collected packages: pyaml, scikit-optimize
Successfully installed pyaml-23.5.9 scikit-optimize-0.9.0

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path = "/content/drive/MyDrive/test.csv"
#df_test = pd.read_csv(path, index_col = 0)
#path_test = '/content/drive/MyDrive/train.csv'
df_train = pd.read_csv(path_test, index_col = 0)

In [ ]:
df_test

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
PassengerId,,,,,,,,,,,,
0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...
9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [ ]:
df_test.isnull().sum()

HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [ ]:
df_test2 = df_test.dropna(axis = 0)

In [ ]:
df_test2.isnull().sum()

HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
dtype: int64

In [ ]:
df_test2

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
PassengerId,,,,,,,,,,,,
0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...
9263_01,Earth,True,G/1495/S,TRAPPIST-1e,43.0,False,0.0,0.0,0.0,0.0,0.0,Loisey Heney
9265_01,Mars,False,D/278/S,TRAPPIST-1e,43.0,False,47.0,0.0,3851.0,0.0,0.0,Toate Cure
9266_01,Earth,False,F/1796/S,TRAPPIST-1e,40.0,False,0.0,865.0,0.0,3.0,0.0,Danna Peter
9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [ ]:
df_test2['HomePlanet'].value_counts()

Earth     1761
Europa     792
Mars       728
Name: HomePlanet, dtype: int64

In [ ]:
encoded = pd.get_dummies(df_test2, columns = ['HomePlanet',"Destination"], drop_first = True)

In [ ]:
encoded

,CryoSleep,Cabin,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,HomePlanet_Europa,HomePlanet_Mars,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
PassengerId,,,,,,,,,,,,,,
0013_01,True,G/3/S,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning,0,0,0,1
0018_01,False,F/4/S,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers,0,0,0,1
0019_01,True,C/0/S,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus,1,0,0,0
0021_01,False,C/1/S,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter,1,0,0,1
0023_01,False,F/5/S,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263_01,True,G/1495/S,43.0,False,0.0,0.0,0.0,0.0,0.0,Loisey Heney,0,0,0,1
9265_01,False,D/278/S,43.0,False,47.0,0.0,3851.0,0.0,0.0,Toate Cure,0,1,0,1
9266_01,False,F/1796/S,40.0,False,0.0,865.0,0.0,3.0,0.0,Danna Peter,0,0,0,1
9266_02,True,G/1496/S,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter,0,0,0,1
9277_01,True,G/1498/S,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley,0,0,1,0

In [ ]:
df_test3 = encoded.drop('Name', axis = 1)

In [ ]:
df_test2

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
PassengerId,,,,,,,,,,,,
0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...
9263_01,Earth,True,G/1495/S,TRAPPIST-1e,43.0,False,0.0,0.0,0.0,0.0,0.0,Loisey Heney
9265_01,Mars,False,D/278/S,TRAPPIST-1e,43.0,False,47.0,0.0,3851.0,0.0,0.0,Toate Cure
9266_01,Earth,False,F/1796/S,TRAPPIST-1e,40.0,False,0.0,865.0,0.0,3.0,0.0,Danna Peter
9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [ ]:

def test(index):
  cabin = df_test2['Cabin'][index].split('/')
  if cabin[2] == 'S':
    df_test2['Cabin'][index] = 1
  elif cabin[2] == 'P':
    df_test2['Cabin'][index] = 0

for x in range(0,3281):
  test(x)

df_test2

<ipython-input-94-5b9ec8774848>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test2['Cabin'][index] = 1
<ipython-input-94-5b9ec8774848>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test2['Cabin'][index] = 0

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
PassengerId,,,,,,,,,,,,
0013_01,Earth,True,1,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
0018_01,Earth,False,1,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
0019_01,Europa,True,1,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
0021_01,Europa,False,1,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
0023_01,Earth,False,1,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...
9263_01,Earth,True,1,TRAPPIST-1e,43.0,False,0.0,0.0,0.0,0.0,0.0,Loisey Heney
9265_01,Mars,False,1,TRAPPIST-1e,43.0,False,47.0,0.0,3851.0,0.0,0.0,Toate Cure
9266_01,Earth,False,1,TRAPPIST-1e,40.0,False,0.0,865.0,0.0,3.0,0.0,Danna Peter
9266_02,Earth,True,1,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
9277_01,Earth,True,1,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [ ]:
df_test2['Cabin'].value_counts()

1    1644
0    1637
Name: Cabin, dtype: int64

###RFC, BAYESIAN METHOD

In [ ]:
df_test2

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
PassengerId,,,,,,,,,,,,
0013_01,Earth,True,1,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
0018_01,Earth,False,1,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
0019_01,Europa,True,1,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
0021_01,Europa,False,1,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
0023_01,Earth,False,1,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...
9263_01,Earth,True,1,TRAPPIST-1e,43.0,False,0.0,0.0,0.0,0.0,0.0,Loisey Heney
9265_01,Mars,False,1,TRAPPIST-1e,43.0,False,47.0,0.0,3851.0,0.0,0.0,Toate Cure
9266_01,Earth,False,1,TRAPPIST-1e,40.0,False,0.0,865.0,0.0,3.0,0.0,Danna Peter
9266_02,Earth,True,1,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
9277_01,Earth,True,1,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [ ]:
df_test3 = pd.get_dummies(df_test2, columns = ['CryoSleep','VIP'], drop_first = True)

In [ ]:
df_test3

,HomePlanet,Cabin,Destination,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,CryoSleep_True,VIP_True
PassengerId,,,,,,,,,,,,
0013_01,Earth,1,TRAPPIST-1e,27.0,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning,1,0
0018_01,Earth,1,TRAPPIST-1e,19.0,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers,0,0
0019_01,Europa,1,55 Cancri e,31.0,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus,1,0
0021_01,Europa,1,TRAPPIST-1e,38.0,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter,0,0
0023_01,Earth,1,TRAPPIST-1e,20.0,10.0,0.0,635.0,0.0,0.0,Brence Harperez,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9263_01,Earth,1,TRAPPIST-1e,43.0,0.0,0.0,0.0,0.0,0.0,Loisey Heney,1,0
9265_01,Mars,1,TRAPPIST-1e,43.0,47.0,0.0,3851.0,0.0,0.0,Toate Cure,0,0
9266_01,Earth,1,TRAPPIST-1e,40.0,0.0,865.0,0.0,3.0,0.0,Danna Peter,0,0
9266_02,Earth,1,TRAPPIST-1e,34.0,0.0,0.0,0.0,0.0,0.0,Jeron Peter,1,0
9277_01,Earth,1,PSO J318.5-22,43.0,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley,1,0

In [ ]:
x = df_tren3.drop('Transported_True', axis = 1)
y = df_tren3['Transported_True']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 101)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = dtc.predict(x_test)
y_pred

array([0, 1, 1, ..., 0, 0, 0], dtype=uint8)

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.70      0.71       968
           1       0.72      0.76      0.74      1014

    accuracy                           0.73      1982
   macro avg       0.73      0.73      0.73      1982
weighted avg       0.73      0.73      0.73      1982

###ACCURACY DECISION TREE

In [ ]:
accuracy_score(y_test, y_pred)

0.727547931382442

In [ ]:
rfc = RandomForestClassifier(n_estimators=100, random_state = 101) #number of decision trees
rfc.fit(x_train,y_train)

RandomForestClassifier(random_state=101)

In [ ]:
rfc_pred = rfc.predict(x_test)
rfc_pred

array([0, 1, 1, ..., 0, 0, 0], dtype=uint8)

###BEST ACCURACY = RFC

In [ ]:
accuracy_score(y_test, rfc_pred)

0.7875882946518667

In [ ]:
param_grid = {'max_depth': [5,6,7,8,9,10,20,40,50,60,70],
              'min_samples_split': [3,4,5,6,7,8,9,10,11,12],
              'criterion': ['gini', 'entropy']
}

In [ ]:
grid = GridSearchCV(dtc, param_grid = param_grid, verbose = 3, refit = True)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 220 candidates, totalling 1100 fits
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=3;, score=0.776 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=3;, score=0.760 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=3;, score=0.785 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=3;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=3;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=4;, score=0.776 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=4;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=4;, score=0.785 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=4;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=4;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=5;, score=0.776 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=5;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=5;, score=0.785 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=5;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=5;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=6;, score=0.776 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=6;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=6;, score=0.785 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=6;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=6;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=7;, score=0.776 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=7;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=7;, score=0.785 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=7;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=7;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=8;, score=0.776 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=8;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=8;, score=0.785 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=8;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=8;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=9;, score=0.776 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=9;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=9;, score=0.785 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=9;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=9;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=10;, score=0.776 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=10;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=10;, score=0.785 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=10;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=10;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=11;, score=0.776 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=11;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=11;, score=0.785 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=11;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=11;, score=0.774 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=5, min_samples_split=12;, score=0.776 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=5, min_samples_split=12;, score=0.760 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=5, min_samples_split=12;, score=0.785 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=5, min_samples_split=12;, score=0.746 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=5, min_samples_split=12;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=3;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=3;, score=0.768 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=3;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=3;, score=0.752 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=3;, score=0.779 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=4;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=4;, score=0.765 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=4;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=4;, score=0.754 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=4;, score=0.779 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=5;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=5;, score=0.765 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=5;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=5;, score=0.752 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=5;, score=0.779 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=6;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=6;, score=0.765 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=6;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=6;, score=0.754 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=6;, score=0.779 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=7;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=7;, score=0.765 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=7;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=7;, score=0.752 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=7;, score=0.779 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=8;, score=0.779 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=8;, score=0.768 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=8;, score=0.776 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=8;, score=0.754 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=8;, score=0.779 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=9;, score=0.779 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=9;, score=0.768 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=9;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=9;, score=0.754 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=9;, score=0.779 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=10;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=10;, score=0.765 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=10;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=10;, score=0.752 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=10;, score=0.779 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=11;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=11;, score=0.765 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=11;, score=0.776 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=11;, score=0.754 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=11;, score=0.779 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=6, min_samples_split=12;, score=0.779 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=6, min_samples_split=12;, score=0.765 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=6, min_samples_split=12;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=6, min_samples_split=12;, score=0.754 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=6, min_samples_split=12;, score=0.779 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=3;, score=0.777 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=3;, score=0.772 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=3;, score=0.788 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=3;, score=0.768 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=3;, score=0.788 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=4;, score=0.778 total time=   0.1s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=4;, score=0.770 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=4;, score=0.787 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=4;, score=0.768 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=4;, score=0.788 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=5;, score=0.778 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=5;, score=0.770 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=5;, score=0.787 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=5;, score=0.766 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=5;, score=0.788 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=6;, score=0.778 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=6;, score=0.770 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=6;, score=0.787 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=6;, score=0.769 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=6;, score=0.788 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=7;, score=0.777 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=7;, score=0.771 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=7;, score=0.787 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=7;, score=0.769 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=7;, score=0.788 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=8;, score=0.777 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=8;, score=0.772 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=8;, score=0.787 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=8;, score=0.766 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=8;, score=0.788 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=9;, score=0.777 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=9;, score=0.770 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=9;, score=0.787 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=9;, score=0.769 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=9;, score=0.788 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=10;, score=0.777 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=10;, score=0.775 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=10;, score=0.788 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=10;, score=0.768 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=10;, score=0.789 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=11;, score=0.777 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=11;, score=0.773 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=11;, score=0.786 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=11;, score=0.770 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=11;, score=0.789 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=7, min_samples_split=12;, score=0.777 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=7, min_samples_split=12;, score=0.771 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=7, min_samples_split=12;, score=0.786 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=7, min_samples_split=12;, score=0.769 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=7, min_samples_split=12;, score=0.789 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=3;, score=0.781 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=3;, score=0.774 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=3;, score=0.782 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=3;, score=0.747 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=3;, score=0.775 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=4;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=4;, score=0.772 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=4;, score=0.781 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=4;, score=0.750 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=4;, score=0.775 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=5;, score=0.779 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=5;, score=0.774 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=5;, score=0.781 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=5;, score=0.751 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=5;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=6;, score=0.784 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=6;, score=0.774 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=6;, score=0.778 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=6;, score=0.749 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=6;, score=0.774 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=7;, score=0.784 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=7;, score=0.772 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=7;, score=0.783 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=7;, score=0.749 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=7;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=8;, score=0.783 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=8;, score=0.774 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=8;, score=0.779 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=8;, score=0.751 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=8;, score=0.774 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=9;, score=0.783 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=9;, score=0.772 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=9;, score=0.781 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=9;, score=0.752 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=9;, score=0.775 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=10;, score=0.783 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=10;, score=0.777 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=10;, score=0.782 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=10;, score=0.751 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=10;, score=0.777 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=11;, score=0.784 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=11;, score=0.772 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=11;, score=0.778 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=11;, score=0.752 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=11;, score=0.777 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=8, min_samples_split=12;, score=0.781 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=8, min_samples_split=12;, score=0.773 total time=   0.1s
[CV 3/5] END criterion=gini, max_depth=8, min_samples_split=12;, score=0.781 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=8, min_samples_split=12;, score=0.754 total time=   0.1s
[CV 5/5] END criterion=gini, max_depth=8, min_samples_split=12;, score=0.779 total time=   0.1s
[CV 1/5] END criterion=gini, max_depth=9, min_samples_split=3;, score=0.763 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=9, min_samples_split=3;, score=0.764 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=9, min_samples_split=3;, score=0.791 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=9, min_samples_split=3;, score=0.755 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=9, min_samples_split=3;, score=0.777 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=9, min_samples_split=4;, score=0.762 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=9, min_samples_split=4;, score=0.766 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=9, min_samples_split=4;, score=0.792 total time=   0.1s
[CV 4/5] END criterion=gini, max_depth=9, min_samples_split=4;, score=0.758 total time=   0.0s

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 6, 7, 8, 9, 10, 20, 40, 50, 60, 70],
                         'min_samples_split': [3, 4, 5, 6, 7, 8, 9, 10, 11,
                                               12]},
             verbose=3)

In [ ]:
grid_preds = grid.predict(x_test)

###GRID SEARCH ACCURACY

In [ ]:
accuracy_score(y_test, grid_preds)

0.781029263370333

In [ ]:
search_space = {'max_depth': (1,200),
              'min_samples_split': (1,10),
              'criterion': ['gini', 'entropy']
}

In [ ]:
opt = BayesSearchCV(estimator = dtc, search_spaces= search_space,scoring = 'neg_mean_squared_error',n_iter = 5,random_state = 100,verbose = 3)

In [ ]:
opt

BayesSearchCV(estimator=DecisionTreeClassifier(), n_iter=5, random_state=100,
              scoring='neg_mean_squared_error',
              search_spaces={'criterion': ['gini', 'entropy'],
                             'max_depth': (1, 200),
                             'min_samples_split': (1, 10)},
              verbose=3)

In [ ]:
opt.fit(x_test, grid_preds)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END criterion=entropy, max_depth=35, min_samples_split=5;, score=-0.035 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=35, min_samples_split=5;, score=-0.025 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=35, min_samples_split=5;, score=-0.040 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=35, min_samples_split=5;, score=-0.025 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=35, min_samples_split=5;, score=-0.040 total time=   0.0s
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END criterion=entropy, max_depth=82, min_samples_split=8;, score=-0.033 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=82, min_samples_split=8;, score=-0.018 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=82, min_samples_split=8;, score=-0.040 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=82, min_samples_split=8;, score=-0.025 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=82, min_samples_split=8;, score=-0.045 total time=   0.0s
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END criterion=entropy, max_depth=109, min_samples_split=8;, score=-0.035 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=109, min_samples_split=8;, score=-0.023 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=109, min_samples_split=8;, score=-0.040 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=109, min_samples_split=8;, score=-0.028 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=109, min_samples_split=8;, score=-0.045 total time=   0.0s
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END criterion=gini, max_depth=64, min_samples_split=6;, score=-0.043 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=64, min_samples_split=6;, score=-0.045 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=64, min_samples_split=6;, score=-0.038 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=64, min_samples_split=6;, score=-0.033 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=64, min_samples_split=6;, score=-0.045 total time=   0.0s
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END criterion=entropy, max_depth=142, min_samples_split=3;, score=-0.033 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=142, min_samples_split=3;, score=-0.023 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=142, min_samples_split=3;, score=-0.035 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=142, min_samples_split=3;, score=-0.023 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=142, min_samples_split=3;, score=-0.038 total time=   0.0s

BayesSearchCV(estimator=DecisionTreeClassifier(), n_iter=5, random_state=100,
              scoring='neg_mean_squared_error',
              search_spaces={'criterion': ['gini', 'entropy'],
                             'max_depth': (1, 200),
                             'min_samples_split': (1, 10)},
              verbose=3)

In [ ]:
predictions = opt.predict(x_test)

In [ ]:
accuracy_score(predictions, y_pred)

0.7971745711402624