In [ ]:
#pytorch

import torch
from torch import nn
import torch.optim as optim

In [ ]:
#regular imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

dataset = load_breast_cancer(as_frame=True)

In [ ]:
df = dataset.frame
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis = 1), df['target'], test_size = 0.3, random_state = 101)

In [ ]:
X_train

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
178,13.010,22.22,82.01,526.4,0.06251,0.01938,0.001595,0.001852,0.1395,0.05234,...,14.00,29.02,88.18,608.8,0.08125,0.03432,0.007977,0.009259,0.2295,0.05843
421,14.690,13.98,98.22,656.1,0.10310,0.18360,0.145000,0.063000,0.2086,0.07406,...,16.46,18.34,114.10,809.2,0.13120,0.36350,0.321900,0.110800,0.2827,0.09208
57,14.710,21.59,95.55,656.9,0.11370,0.13650,0.129300,0.081230,0.2027,0.06758,...,17.87,30.70,115.70,985.5,0.13680,0.42900,0.358700,0.183400,0.3698,0.10940
514,15.050,19.07,97.26,701.9,0.09215,0.08597,0.074860,0.043350,0.1561,0.05915,...,17.58,28.06,113.80,967.0,0.12460,0.21010,0.286600,0.112000,0.2282,0.06954
548,9.683,19.34,61.05,285.7,0.08491,0.05030,0.023370,0.009615,0.1580,0.06235,...,10.93,25.59,69.10,364.2,0.11990,0.09546,0.093500,0.038460,0.2552,0.07920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,12.770,29.43,81.35,507.9,0.08276,0.04234,0.019970,0.014990,0.1539,0.05637,...,13.87,36.00,88.10,594.7,0.12340,0.10640,0.086530,0.064980,0.2407,0.06484
393,21.610,22.28,144.40,1407.0,0.11670,0.20870,0.281000,0.156200,0.2162,0.06606,...,26.23,28.74,172.00,2081.0,0.15020,0.57170,0.705300,0.242200,0.3828,0.10070
75,16.070,19.65,104.10,817.7,0.09168,0.08424,0.097690,0.066380,0.1798,0.05391,...,19.77,24.56,128.80,1223.0,0.15000,0.20450,0.282900,0.152000,0.2650,0.06387
337,18.770,21.43,122.90,1092.0,0.09116,0.14020,0.106000,0.060900,0.1953,0.06083,...,24.54,34.37,161.10,1873.0,0.14980,0.48270,0.463400,0.204800,0.3679,0.09870
523,13.710,18.68,88.73,571.0,0.09916,0.10700,0.053850,0.037830,0.1714,0.06843,...,15.11,25.63,99.43,701.9,0.14250,0.25660,0.193500,0.128400,0.2849,0.09031

In [ ]:
X_train_mean = np.mean(X_train)
X_train_std = np.std(X_train)
X_train_norm = (X_train - X_train_mean)/X_train_std

X_test_mean = np.mean(X_test)
X_test_std = np.std(X_test)
X_test_norm = (X_test - X_test_mean)/X_test_std

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3472: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3472: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)

In [ ]:
X_train_norm

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
178,-0.281922,0.661742,-0.374316,-0.336899,-2.403936,-1.596284,-1.064755,-1.185896,-1.541548,-1.489822,...,-0.435134,0.499128,-0.534098,-0.446176,-2.268100,-1.403780,-1.233516,-1.571631,-0.987646,-1.430161
421,0.186501,-1.221863,0.282336,0.026268,0.483232,1.507682,0.684032,0.380349,1.000947,1.520692,...,0.062055,-1.207228,0.221605,-0.106431,-0.066706,0.680186,0.210404,-0.053966,-0.136910,0.386852
57,0.192078,0.517728,0.174177,0.028509,1.237211,0.617432,0.492574,0.847292,0.783860,0.622527,...,0.347029,0.767544,0.268254,0.192457,0.180097,1.094851,0.379669,1.031137,1.255930,1.322088
514,0.286878,-0.058326,0.243447,0.154511,-0.295642,-0.337649,-0.171307,-0.122966,-0.930760,-0.545918,...,0.288417,0.345748,0.212859,0.161093,-0.357581,-0.290956,0.048038,-0.036030,-1.008435,-0.830250
548,-1.209567,0.003394,-1.223386,-1.010872,-0.810623,-1.011857,-0.799215,-0.987055,-0.860851,-0.102380,...,-1.055610,-0.048887,-1.090380,-0.860855,-0.564719,-1.016716,-0.840144,-1.135183,-0.576670,-0.308635
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,-0.348840,2.309897,-0.401052,-0.388700,-0.963553,-1.162311,-0.840677,-0.849379,-1.011708,-0.931242,...,-0.461409,1.614332,-0.536430,-0.470080,-0.410467,-0.947457,-0.872203,-0.738807,-0.808544,-1.084038
393,2.115959,0.675458,2.153045,2.128830,1.450601,1.982104,2.342517,2.767574,1.280585,0.411847,...,2.036664,0.454393,1.909692,2.049696,0.770661,1.998253,1.973890,1.909981,1.463816,0.852310
75,0.571278,0.074258,0.520529,0.478757,-0.329073,-0.370348,0.107099,0.466924,-0.058732,-1.272211,...,0.731037,-0.213451,0.650187,0.595099,0.761847,-0.326408,0.031020,0.561822,-0.419956,-1.136415
337,1.324101,0.481154,1.282100,1.246813,-0.366061,0.687367,0.208437,0.326559,0.511581,-0.313061,...,1.695099,1.353904,1.591901,1.697067,0.753032,1.434814,0.861247,1.350988,1.225546,0.744315
523,-0.086746,-0.147477,-0.102095,-0.212016,0.202980,0.059845,-0.427519,-0.264356,-0.367806,0.740342,...,-0.210793,-0.042496,-0.206102,-0.288340,0.431307,0.003425,-0.380184,0.209089,-0.101729,0.291277

In [ ]:
X_train_norm.values.shape

(398, 30)

In [ ]:
X_train = torch.tensor(X_train_norm.values, dtype=torch.float)
y_train = torch.tensor(y_train.values, dtype=torch.long)
X_test = torch.tensor(X_test_norm.values, dtype=torch.float)
y_test = torch.tensor(y_test.values, dtype=torch.long)

In [ ]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.hidden1 = nn.Linear(X_train.shape[1], 16)
    self.hidden2 = nn.Linear(16, 2)

  def forward(self, x):
    x = torch.relu(self.hidden1(x))
    x = self.hidden2(x)
    return x

In [ ]:
model = NeuralNetwork()
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)
print(model)

NeuralNetwork(
  (hidden1): Linear(in_features=30, out_features=16, bias=True)
  (hidden2): Linear(in_features=16, out_features=2, bias=True)
)

In [ ]:
from torch.utils.data import DataLoader, TensorDataset

In [ ]:
train_data = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_data, batch_size = 32)

In [ ]:
epochs = 200
loss_list = np.zeros((epochs,))

for epoch in range(epochs):
  running_loss = 0
  for inputs, targets in train_loader:
    optimizer.zero_grad() # reset optimizer gradients
    outputs = model(inputs) # forward pass data through nodes/layers
    loss = loss_fn(outputs, targets) # compute loss
    loss_list[epoch] = loss.item()
    running_loss += loss.item()
    loss.backward() # backprop
    optimizer.step() # update weighst

  if epoch % 10 == 0:
    print(f'Epoch [{epoch}/100], Loss: {running_loss/len(train_loader)}')

Epoch [0/100], Loss: 0.714099448460799
Epoch [10/100], Loss: 0.6402510267037612
Epoch [20/100], Loss: 0.583356458407182
Epoch [30/100], Loss: 0.5374786532842196
Epoch [40/100], Loss: 0.4973853528499603
Epoch [50/100], Loss: 0.46025965305475086
Epoch [60/100], Loss: 0.4258974836422847
Epoch [70/100], Loss: 0.3943900488890134
Epoch [80/100], Loss: 0.36571803230505723
Epoch [90/100], Loss: 0.33965351948371303
Epoch [100/100], Loss: 0.31619011668058544
Epoch [110/100], Loss: 0.29528558254241943
Epoch [120/100], Loss: 0.2766645894600795
Epoch [130/100], Loss: 0.2600995416824634
Epoch [140/100], Loss: 0.24537504750948685
Epoch [150/100], Loss: 0.23230696870730475
Epoch [160/100], Loss: 0.2206851725394909
Epoch [170/100], Loss: 0.21029362311730018
Epoch [180/100], Loss: 0.20105194472349608
Epoch [190/100], Loss: 0.19273139307132134

In [ ]:
with torch.no_grad():
  out = model(X_test)
  _, predicted = torch.max(out.data, 1)
  total = y_test.size(0)
  correct = (predicted == y_test).sum().item()
  print("Accuracy of the model based on y_test: {}%".format(100 * correct/total))

Accuracy of the model based on y_test: 92.98245614035088%